# Generated by Django 5.0.4 on 2024-05-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.CharField(max_length=40)),
                ('service_title', models.CharField(max_length=40)),
                ('service_des', models.TextField()),
            ],
        ),
    ]
