# Generated by Django 5.0.4 on 2024-05-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_icon', models.CharField(max_length=50)),
                ('skill_title', models.CharField(max_length=50)),
            ],
        ),
    ]
