# Generated by Django 5.0.4 on 2024-05-06 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill_icon_style',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
